#!python

from libre import LibreText, LibreManager 

import argparse
import os

parser = argparse.ArgumentParser(description='LiBRE! Manager')
parser.add_argument('--username', help="Specify username", required=True)
parser.add_argument('--password', help="Specify password", required=True)
parser.add_argument("--page", help="Specify page to operate on", required=True)
parser.add_argument("--action", help="Specify action (get, linking)", required=True)
args = parser.parse_args()

manager = LibreManager(args.username, args.password) 

if args.action == "get": 
	print manager.getPage(args.page) 
elif args.action == "linking": 
	texts = manager.getAllLinked(args.page) 
	print "_____________________________________________________________"
	homepath = os.getenv("HOME", "/home")
	path = os.getenv("LIBRE_DEFAULT_DATABASE", homepath + "/LiBRE-work/" + args.page + "/")
	for text in texts: 
		if text.getTitle().strip() != "": 
			filename = text.getTitle().encode("utf8") + ".html"
			if os.path.exists(path + filename): 
				filename = text.getTitle().encode("utf8") + "_" + ".html"
			f = open(path + filename, "w")
			f.write(text.getHTML().encode("utf8"))
			f.close()
	
		
else: 
	print "Bad action selected. "
